version = 1

exclude_patterns = [
  "arxiv_vanity/papers/migrations/**"
]

test_patterns = [
  "arxiv_vanity/papers/tests/**",
  "arxiv_vanity/scraper/tests/**",
  "arxiv_vanity/tests/**"
]

[[analyzers]]
name = "python"
enabled = true
runtime_version = "3.x.x"
