# Generated by Django 2.0.7 on 2018-08-02 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Render',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(choices=[('unstarted', 'Unstarted'), ('running', 'Running'), ('success', 'Success'), ('failure', 'Failure')], default='unstarted', max_length=20)),
                ('logs', models.TextField(blank=True, null=True)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renders', to='papers.Paper')),
            ],
            options={
                'get_latest_by': 'created_at',
            },
        ),
    ]
