# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 20:13
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("papers", "0003_auto_20170816_1457")]

    operations = [
        migrations.AddField(
            model_name="render",
            name="container_inspect",
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="render",
            name="container_logs",
            field=models.TextField(blank=True, null=True),
        ),
    ]
