# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 15:47
from __future__ import unicode_literals

from django.db import migrations


def shorten_arxiv_id(apps, schema_editor):
    Paper = apps.get_model('papers', 'Paper')
    for paper in Paper.objects.all():
        paper.arxiv_id = paper.arxiv_id.split('/')[-1]
        paper.save()


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0004_auto_20170818_2013'),
    ]

    operations = [
        migrations.RunPython(shorten_arxiv_id)
    ]
