# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("papers", "0005_auto_20170822_1547")]

    operations = [
        migrations.AlterField(
            model_name="paper",
            name="arxiv_id",
            field=models.CharField(max_length=50, unique=True),
        )
    ]
