# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0007_auto_20170904_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='render',
            name='container_is_removed',
            field=models.BooleanField(default=False),
        ),
    ]
