# Generated by Django 2.0.1 on 2018-01-11 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0010_render_is_expired'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='source-files/')),
            ],
        ),
        migrations.CreateModel(
            name='SourceFileBulkTarball',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, unique=True)),
                ('content_md5sum', models.TextField()),
                ('first_item', models.TextField()),
                ('last_item', models.TextField()),
                ('md5sum', models.TextField()),
                ('num_items', models.IntegerField()),
                ('seq_num', models.IntegerField()),
                ('size', models.IntegerField()),
                ('timestamp', models.TextField()),
                ('yymm', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='sourcefile',
            name='bulk_tarball',
            field=models.ForeignKey(blank=True, help_text="If this source file is from Arxiv's bulk download service, this is the tarball it was in.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='papers.SourceFileBulkTarball'),
        ),
    ]
