# Generated by Django 2.0.1 on 2018-01-12 17:19

from collections import defaultdict
from django.db import migrations, transaction, IntegrityError


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0013_paper_is_deleted'),
    ]

    operations = [
    ]
