# Generated by Django 2.0.1 on 2018-01-17 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0014_remove_version_from_arxiv_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcefile',
            name='file',
            field=models.FileField(unique=True, upload_to='source-files/'),
        ),
    ]
