# Generated by Django 2.0.6 on 2018-06-19 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0015_auto_20180117_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcefile',
            name='arxiv_id',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='sourcefile',
            name='bulk_tarball',
            field=models.ForeignKey(blank=True, help_text="If this source file is from Arxiv's bulk download service, this is the tarball it was in. If null, this source file was downloaded individually.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='papers.SourceFileBulkTarball'),
        ),
    ]
