# Generated by Django 2.0.6 on 2018-06-20 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("papers", "0017_auto_20180619_1657")]

    operations = [
        migrations.AlterField(
            model_name="sourcefile",
            name="arxiv_id",
            field=models.CharField(max_length=50, unique=True),
        )
    ]
