# Generated by Django 2.0.6 on 2018-06-20 13:03

from django.db import migrations
from arxiv_vanity.scraper.bulk_sources import convert_source_file_to_arxiv_id


# This is a fixed version of 0017, which didn't work as expected
def generate_arxiv_ids(apps, schema_editor):
    SourceFile = apps.get_model('papers', 'SourceFile')
    for sf in SourceFile.objects.iterator():
        sf.arxiv_id = convert_source_file_to_arxiv_id(sf.file.name)
        sf.save()


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0018_auto_20180620_1001'),
    ]

    operations = [
        migrations.RunPython(generate_arxiv_ids),
    ]
