# Generated by Django 2.0.6 on 2018-06-20 13:03

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0018_auto_20180620_1001'),
    ]

    operations = [
    ]
