# Generated by Django 2.0.6 on 2018-06-21 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("papers", "0019_auto_20180620_1303")]

    operations = [
        migrations.RenameField(
            model_name="paper", old_name="source_file", new_name="source_file_old"
        )
    ]
