# Generated by Django 2.2.8 on 2020-01-23 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0023_auto_20200121_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='doi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='journal_ref',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
