# Generated by Django 2.2.10 on 2020-04-18 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0024_auto_20200123_2008'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paper',
            options={'get_latest_by': 'updated'},
        ),
        migrations.AlterField(
            model_name='paper',
            name='updated',
            field=models.DateTimeField(db_index=True),
        ),
    ]
