# Generated by Django 2.2.13 on 2021-01-06 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0026_auto_20201231_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
