# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 14:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0002_auto_20170815_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='source_file',
            field=models.FileField(blank=True, null=True, upload_to='paper-sources/'),
        ),
        migrations.AlterField(
            model_name='render',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renders', to='papers.Paper'),
        ),
    ]
